### PR TITLE
Adding Model Tree Visualisation with Lines Between Bodies

### PR DESCRIPTION
**Pull request by ju6ge**
Simple Model Tree Visualisation for model development purposes.

image_full
image_modeltree

### CODE REVIEW

**Comment by jfslin** [comment]
image

Well. It seems like our REEM C has lost a lot of weight... but this looks good. Maybe thicker lines and not white so it's easier differentiate from the ground?

**Comment by jfslin** [comment]
image

So this image is pretty cluttered, but it's the visualizer that I used to use from a previous lab. It's not quite comparable because the MATLAB code uses the Kalman filter to fill in gaps in markers and has some ability to ignore misnamed markers, so we needed a lot more visual elements to check how well it works. I don't want to make the toolkit UI too cluttered, but this is where I am coming from in terms of potential UI elements to add. 

image

This one is a zoom in of the elbow. 
- The cylinders are DOFs in RGB order if concentric
- Blue links are the limbs
- Magenta boxes are modelmarkers
- Yellow circle are the actual markers

Do you think any of these would be useful? I am assuming a lot of the models likely would have meshes that comes with them so maybe this is not a important point for now

**Comment by ju6ge** [comment]
Okay now the width and color of the model tree segments is adjustable in the toolkit settings. I also want to add frame axis to every joint, that has been one of the features of meshup that i wanted to port for a long time and have not gotten around to.

**Comment by jfslin** [comment]
Commit 4118060 builds without a problem via CLI cmake on my side. The image show the reemc_uw.urdf model. 

image

**Pull request merged**
